[workspace]
members = [
  "apps/crown",
  "apps/metapixel",
  "apps/testapp",
  "apps/tiles",
  "apps/twocolor",
  "libs/bootstrap",
  "libs/components",
  "libs/grids",
  "libs/renderer",
  "libs/tools",
  "serving",
]
