[package]
name = "twopattern"
version = "0.7.0"
authors = ["George Madrid <gmadrid@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
wasm-bindgen = "0.2"
yew = "0.17"

[dependencies.yewknit]
path = "../yewknit"
