[tasks.default]
alias = "twopattern-bundle"

[tasks.wasm]
description = "Build the wasm code"
command = "wasm-pack"
args = ["build", "--target", "web"]
dependencies = [ "format" ]
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "--help" }

[tasks.twopattern-bundle]
description = "Bundle the wasm"
dependencies = [ "wasm" ]
command = "rollup"
args = [ "./twocolor.js", "--format", "iife", "--file", "./pkg/twocolor.js" ]

[tasks.metapixel-bundle]
description = "Bundle the wasm"
dependencies = [ "wasm" ]
command = "rollup"
args = [ "./other.js", "--format", "iife", "--file", "./pkg/other.js" ]

[tasks.all-bundles]
dependencies = ["twopattern-bundle", "metapixel-bundle"]

[tasks.watch-all-bundles]
dependencies = ["all-bundles"]
watch = { postpone = true, no_git_ignore = true, watch = ["./src"] }

[tasks.clean-pkg]
description = "Clean out the /pkg directory"
command = "rm"
args = [ "-rf", "pkg" ]

[tasks.make-dist]
dependencies = ["clean", "clean-pkg", "twopattern-bundle"]
command = "zip"
args = [ "-r", "dist-${CARGO_MAKE_CRATE_VERSION}.zip", "index.html", "pkg" ]
